### ISSUE TITLE
Implementacja UI

### ISSUE THREAD

**Issue by agngan** [AvaPL/Reservatio#12]
- [x] widok rejestracji i logowania #20 
- [x] pasek nawigacji wraz z routingem #21 

Perspektywa użytkownika:
- [x] widoki Explore, Search, Favourites #22 
- [x] widok Appointments #23 
- [x] widok szczegółów salonu (informacje, opinie) #24 
- [x] widok rezerwacji #25 

Perspektywa usługodawcy:
- [x] widok Statistics
- [x] widok Employees (trzeba go też dodać do makiet, bo nie powstał)
- [x] widok rezerwacji (trzeba go też dodać do makiet i navbara)
- [x] widok Services
- [x] widok Profile

Makiety dla użytkownika:
Dekstop - https://app.moqups.com/QuYnmGUEhD/view/page/ad64222d5
Mobilne - https://app.moqups.com/2zhmYhZBCA/view/page/ae8fe8eb0

Makiety dla usługodawcy:
Dekstop - https://app.moqups.com/z4ZpUfI3Lh/view/page/ad64222d5
Mobilne - https://app.moqups.com/1h99I7rnrH/view/page/ae8fe8eb0

**Comment by agngan** [comment]
Widok rejestracji i logowania

**Comment by Urbekk** [comment]
Appointments

**Comment by rbuszko** [comment]
widok szczegółów salonu (informacje, opinie)

**Comment by AvaPL** [comment]
pasek nawigacji wraz z routingem

**Comment by AvaPL** [comment]
Robert - widoki Explore, Search, Favourites

**Comment by matgwi96** [comment]
Mateusz - Widok rezerwacji
